# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dKWBn4byAnRuY3UWTYQMe2NEiH-6NeF5
"""

import pandas as pd

df = pd.read_csv ('train.csv')

df.loc[10:20]

df.iloc[10:21]

df.loc[5:15, 'Name': 'Age']

df.iloc [50: 101, 2:10]

df.loc[:, 'Name': 'Age']

